'use strict';

const { Miniquest } = require('../Structures');

class Miniquests {
    constructor() {
        this.barCrawl = new Miniquest(`Bar Crawl`);
        this.battleOfTheMonolith = new Miniquest({ name: `Battle of the Monolith` });
        this.benedictsWorldTour = new Miniquest({ name: `Benedict\'s World Tour` });
        this.boricsTaskI = new Miniquest({ name: `Boric\'s Task I` });
        this.boricsTaskII = new Miniquest({ name: `Boric\'s Task II` });
        this.boricsTaskIII = new Miniquest({ name: `Boric\'s Task III` });
        this.theCurseOfZaros = new Miniquest({ name: `The Curse of Zaros` });
        this.DamageControl = new Miniquest({ name: `Damage Control` });
        this.DesertSlayerDungeon = new Miniquest({ name: `Desert Slayer Dungeon` });
        this.DoricsTaskI = new Miniquest({ name: `Doric\'s Task I` });
        this.DoricsTaskII = new Miniquest({ name: `Doric\'s Task II` });
        this.DoricsTaskIII = new Miniquest({ name: `Doric\'s Task III` });
        this.DoricsTaskIV = new Miniquest({ name: `Doric\'s Task IV` });
        this.DoricsTaskV = new Miniquest({ name: `Doric\'s Task V` });
        this.DoricsTaskVI = new Miniquest({ name: `Doric\'s Task VI` });
        this.DoricsTaskVII = new Miniquest({ name: `Doric\'s Task VII` });
        this.DoricsTaskVIII = new Miniquest({ name: `Doric\'s Task VIII` });
        this.EnterTheAbyss = new Miniquest({ name: `Enter the Abyss` });
        this.EyeForAnEye = new Miniquest({ name: `Eye for an Eye` });
        this.EyeOfHetI = new Miniquest({ name: `Eye of Het I` });
        this.EyeOfHetII = new Miniquest({ name: `Eye of Het II` });
        this.FatherAndSon = new Miniquest({ name: `Father and Son` });
        this.FinalDestination = new Miniquest({ name: `Final Destination` });
        this.FlagFall = new Miniquest({ name: `Flag Fall` });
        this.FromTinyAcorns = new Miniquest({ name: `From Tiny Acorns` });
        this.TheGeneralsShadow = new Miniquest({ name: `The General\'s Shadow` });
        this.GhostsFromThePast = new Miniquest({ name: `Ghosts from the Past` });
        this.AGuildOfOurOwn = new Miniquest({ name: `A Guild of Our Own` });
        this.Harbinger = new Miniquest({ name: `Harbinger` });
        this.HeadOfTheFamily = new Miniquest({ name: `Head of the Family` });
        this.HelpingLaniakea = new Miniquest({ name: `Helping Laniakea` });
        this.HopespearsWill = new Miniquest({ name: `Hopespear\'s Will` });
        this.TheHuntForSurok = new Miniquest({ name: `The Hunt` });
        this.InMemoryOfTheMyreque = new Miniquest({ name: `In Memory of the Myreque` });
        this.JedHunter = new Miniquest({ name: `Jed Hunter` });
        this.KoscheisTroubles = new Miniquest({ name: `Koschei\'s Troubles` });
        this.LairOfTarnRazorlor = new Miniquest({ name: `Lair of Tarn Razorlor` });
        this.LostHerMarbles = new Miniquest({ name: `Lost Her Marbles` });
        this.TheLostToys = new Miniquest({ name: `The Lost Toys` });
        this.MahjarratMemories = new Miniquest({ name: `Mahjarrat Memories` });
        this.Nadir = new Miniquest({ name: `Nadir` });
        this.OneFootInTheGrave = new Miniquest({ name: `One Foot` });
        this.PurpleCat = new Miniquest({ name: `Purple Cat` });
        this.RakshatheShadowColossus = new Miniquest({ name: `Raksha, the Shadow Colossus` });
        this.RebuildingEdgeville = new Miniquest({ name: `Rebuilding Edgeville` });
        this.SheepShearer = new Miniquest({ name: `Sheep Shearer` });
        this.SinsOfTheFather = new Miniquest({ name: `Sins of the Father` });
        this.SpiritualEnlightenment = new Miniquest({ name: `Spiritual Enlightenment` });
        this.TalesOfNomad = new Miniquest({ name: `Tales of Nomad` });
        this.TalesOfTheGodWars = new Miniquest({ name: `Tales of the God Wars` });
        this.ThokItToEm = new Miniquest({ name: `Thok It To \'Em` });
        this.ThokYourBlockOff = new Miniquest({ name: `Thok Your Block Off` });
        this.ThreesCompany = new Miniquest({ name: `Three\'s Company` });
        this.TortleCombat = new Miniquest({ name: `Tortle Combat` });
        this.TuaiLeitsOwn = new Miniquest({ name: `Tuai Leit\'s Own` });
        this.TheVaultOfShadows = new Miniquest({ name: `The Vault of Shadows` });
        this.Vengeance = new Miniquest({ name: `Vengeance` });
        this.WanderingGaAl = new Miniquest({ name: `Wandering Ga\'al` });
        this.WitchsPotion = new Miniquest({ name: `Witch\'s Potion` });
    };
};

module.exports = new Miniquests();