'use strict';

const { Miniquest } = require('../Structures');

class Miniquests {
    constructor() {
        this.barCrawl = new Miniquest(`Bar Crawl`);
        this.battleOfTheMonolith = new Miniquest(`Battle of the Monolith`);
        this.benedictsWorldTour = new Miniquest(`Benedict\'s World Tour`);
        this.boricsTaskI = new Miniquest(`Boric\'s Task I`);
        this.boricsTaskII = new Miniquest(`Boric\'s Task II`);
        this.boricsTaskIII = new Miniquest(`Boric\'s Task III`);
        this.theCurseOfZaros = new Miniquest(`The Curse of Zaros`);
        this.DamageControl = new Miniquest(`Damage Control`);
        this.DesertSlayerDungeon = new Miniquest(`Desert Slayer Dungeon`);
        this.DoricsTaskI = new Miniquest(`Doric\'s Task I`);
        this.DoricsTaskII = new Miniquest(`Doric\'s Task II`);
        this.DoricsTaskIII = new Miniquest(`Doric\'s Task III`);
        this.DoricsTaskIV = new Miniquest(`Doric\'s Task IV`);
        this.DoricsTaskV = new Miniquest(`Doric\'s Task V`);
        this.DoricsTaskVI = new Miniquest(`Doric\'s Task VI`);
        this.DoricsTaskVII = new Miniquest(`Doric\'s Task VII`);
        this.DoricsTaskVIII = new Miniquest(`Doric\'s Task VIII`);
        this.EnterTheAbyss = new Miniquest(`Enter the Abyss`);
        this.EyeForAnEye = new Miniquest(`Eye for an Eye`);
        this.EyeOfHetI = new Miniquest(`Eye of Het I`);
        this.EyeOfHetII = new Miniquest(`Eye of Het II`);
        this.FatherAndSon = new Miniquest(`Father and Son`);
        this.FinalDestination = new Miniquest(`Final Destination`);
        this.FlagFall = new Miniquest(`Flag Fall`);
        this.FromTinyAcorns = new Miniquest(`From Tiny Acorns`);
        this.TheGeneralsShadow = new Miniquest(`The General\'s Shadow`);
        this.GhostsFromThePast = new Miniquest(`Ghosts from the Past`);
        this.AGuildOfOurOwn = new Miniquest(`A Guild of Our Own`);
        this.Harbinger = new Miniquest(`Harbinger`);
        this.HeadOfTheFamily = new Miniquest(`Head of the Family`);
        this.HelpingLaniakea = new Miniquest(`Helping Laniakea`);
        this.HopespearsWill = new Miniquest(`Hopespear\'s Will`);
        this.TheHuntForSurok = new Miniquest(`The Hunt`);
        this.InMemoryOfTheMyreque = new Miniquest(`In Memory of the Myreque`);
        this.JedHunter = new Miniquest(`Jed Hunter`);
        this.KoscheisTroubles = new Miniquest(`Koschei\'s Troubles`);
        this.LairOfTarnRazorlor = new Miniquest(`Lair of Tarn Razorlor`);
        this.LostHerMarbles = new Miniquest(`Lost Her Marbles`);
        this.TheLostToys = new Miniquest(`The Lost Toys`);
        this.MahjarratMemories = new Miniquest(`Mahjarrat Memories`);
        this.Nadir = new Miniquest(`Nadir`);
        this.OneFootInTheGrave = new Miniquest(`One Foot`);
        this.PurpleCat = new Miniquest(`Purple Cat`);
        this.RakshatheShadowColossus = new Miniquest(`Raksha, the Shadow Colossus`);
        this.RebuildingEdgeville = new Miniquest(`Rebuilding Edgeville`);
        this.SheepShearer = new Miniquest(`Sheep Shearer`);
        this.SinsOfTheFather = new Miniquest(`Sins of the Father`);
        this.SpiritualEnlightenment = new Miniquest(`Spiritual Enlightenment`);
        this.TalesOfNomad = new Miniquest(`Tales of Nomad`);
        this.TalesOfTheGodWars = new Miniquest(`Tales of the God Wars`);
        this.ThokItToEm = new Miniquest(`Thok It To \'Em`);
        this.ThokYourBlockOff = new Miniquest(`Thok Your Block Off`);
        this.ThreesCompany = new Miniquest(`Three\'s Company`);
        this.TortleCombat = new Miniquest(`Tortle Combat`);
        this.TuaiLeitsOwn = new Miniquest(`Tuai Leit\'s Own`);
        this.TheVaultOfShadows = new Miniquest(`The Vault of Shadows`);
        this.Vengeance = new Miniquest(`Vengeance`);
        this.WanderingGaAl = new Miniquest(`Wandering Ga\'al`);
        this.WitchsPotion = new Miniquest(`Witch\'s Potion`);

    };
};

module.exports = new Miniquests();