'use strict';

const { Miniquest } = require('../Structures');

class Miniquests {
    constructor() {
        this.barCrawl = new Miniquest({ name: `Bar Crawl`, members: true });
        this.battleOfTheMonolith = new Miniquest({ name: `Battle of the Monolith`, members: true });
        this.benedictsWorldTour = new Miniquest({ name: `Benedict\'s World Tour`, members: false });
        this.boricsTaskI = new Miniquest({ name: `Boric\'s Task I`, members: true });
        this.boricsTaskII = new Miniquest({ name: `Boric\'s Task II`, members: true });
        this.boricsTaskIII = new Miniquest({ name: `Boric\'s Task III`, members: true });
        this.theCurseOfZaros = new Miniquest({ name: `The Curse of Zaros`, members: true });
        this.DamageControl = new Miniquest({ name: `Damage Control`, members: true });
        this.DesertSlayerDungeon = new Miniquest({ name: `Desert Slayer Dungeon` });
        this.DoricsTaskI = new Miniquest({ name: `Doric\'s Task I`, members: false });
        this.DoricsTaskII = new Miniquest({ name: `Doric\'s Task II`, members: false });
        this.DoricsTaskIII = new Miniquest({ name: `Doric\'s Task III`, members: false });
        this.DoricsTaskIV = new Miniquest({ name: `Doric\'s Task IV`, members: false });
        this.DoricsTaskV = new Miniquest({ name: `Doric\'s Task V`, members: true });
        this.DoricsTaskVI = new Miniquest({ name: `Doric\'s Task VI`, members: true });
        this.DoricsTaskVII = new Miniquest({ name: `Doric\'s Task VII`, members: true });
        this.DoricsTaskVIII = new Miniquest({ name: `Doric\'s Task VIII`, members: true });
        this.EnterTheAbyss = new Miniquest({ name: `Enter the Abyss`, members: true });
        this.EyeForAnEye = new Miniquest({ name: `Eye for an Eye`, members: true });
        this.EyeOfHetI = new Miniquest({ name: `Eye of Het I`, members: true });
        this.EyeOfHetII = new Miniquest({ name: `Eye of Het II`, members: true });
        this.FatherAndSon = new Miniquest({ name: `Father and Son`, members: true });
        this.FinalDestination = new Miniquest({ name: `Final Destination`, members: true });
        this.FlagFall = new Miniquest({ name: `Flag Fall`, members: true });
        this.FromTinyAcorns = new Miniquest({ name: `From Tiny Acorns`, members: true });
        this.TheGeneralsShadow = new Miniquest({ name: `The General\'s Shadow`, members: true });
        this.GhostsFromThePast = new Miniquest({ name: `Ghosts from the Past`, members: true });
        this.AGuildOfOurOwn = new Miniquest({ name: `A Guild of Our Own`, members: true });
        this.Harbinger = new Miniquest({ name: `Harbinger`, members: true });
        this.HeadOfTheFamily = new Miniquest({ name: `Head of the Family`, members: true });
        this.HelpingLaniakea = new Miniquest({ name: `Helping Laniakea`, members: true });
        this.HopespearsWill = new Miniquest({ name: `Hopespear\'s Will`, members: true });
        this.TheHuntForSurok = new Miniquest({ name: `The Hunt`, members: true });
        this.InMemoryOfTheMyreque = new Miniquest({ name: `In Memory of the Myreque`, members: true });
        this.JedHunter = new Miniquest({ name: `Jed Hunter`, members: true });
        this.KoscheisTroubles = new Miniquest({ name: `Koschei\'s Troubles`, members: true });
        this.LairOfTarnRazorlor = new Miniquest({ name: `Lair of Tarn Razorlor`, members: true });
        this.LostHerMarbles = new Miniquest({ name: `Lost Her Marbles`, members: true });
        this.TheLostToys = new Miniquest({ name: `The Lost Toys`, members: true });
        this.MahjarratMemories = new Miniquest({ name: `Mahjarrat Memories`, members: true });
        this.Nadir = new Miniquest({ name: `Nadir`, members: true });
        this.OneFootInTheGrave = new Miniquest({ name: `One Foot`, members: true });
        this.PurpleCat = new Miniquest({ name: `Purple Cat`, members: false });
        this.RakshatheShadowColossus = new Miniquest({ name: `Raksha, the Shadow Colossus`, members: true });
        this.RebuildingEdgeville = new Miniquest({ name: `Rebuilding Edgeville`, members: true });
        this.SheepShearer = new Miniquest({ name: `Sheep Shearer`, members: false });
        this.SinsOfTheFather = new Miniquest({ name: `Sins of the Father`, members: true });
        this.SpiritualEnlightenment = new Miniquest({ name: `Spiritual Enlightenment`, members: true });
        this.TalesOfNomad = new Miniquest({ name: `Tales of Nomad`, members: true });
        this.TalesOfTheGodWars = new Miniquest({ name: `Tales of the God Wars`, members: true });
        this.ThokItToEm = new Miniquest({ name: `Thok It To \'Em`, members: true });
        this.ThokYourBlockOff = new Miniquest({ name: `Thok Your Block Off`, members: true });
        this.ThreesCompany = new Miniquest({ name: `Three\'s Company`, members: false });
        this.TortleCombat = new Miniquest({ name: `Tortle Combat`, members: true });
        this.TuaiLeitsOwn = new Miniquest({ name: `Tuai Leit\'s Own`, members: true });
        this.TheVaultOfShadows = new Miniquest({ name: `The Vault of Shadows`, members: true });
        this.Vengeance = new Miniquest({ name: `Vengeance`, members: true });
        this.WanderingGaAl = new Miniquest({ name: `Wandering Ga\'al`, members: true });
        this.WitchsPotion = new Miniquest({ name: `Witch\'s Potion`, members: false });
    };
};

module.exports = new Miniquests();